package servent.message;

public enum MessageType {
	NEW_NODE, WELCOME, SORRY, UPDATE, ADD, HANDLE_LOCK, UNLOCK, COMMIT, REMOVE, QUIT, HAND_OVER_VALUES, 
	UPDATE_PREDECESSOR, PUSH, PULL_CONFLICT, PULL,
	PULL_ANSWER,
	UPDATE_VERSION_AFTER_CONFLICT, POISON, SUCCESSOR_ANSWER,
	COMMIT_RESPONSE
}
